### ISSUE TITLE
Import Game Server

### ISSUE THREAD

**Issue by tuvok81** [ohmcodes/WindowsGSM.Sunkenland#1]
hey i have the Problem for this Plugin to import a existent Server

![grafik](https://github.com/ohmcodes/WindowsGSM.Sunkenland/assets/30367063/4e61948a-6a12-45ae-8021-1548965ef1f8)
can anybody help me for this Problem?

**Comment by ohmcodes** [comment]
> have the Problem for this Plugin to import a existent Server

just copy the saved folder after installing a new on WGSM
