### ISSUE TITLE
Something wrong with this plugin. Cant install Sunken Land at all.

### ISSUE THREAD

**Issue by ghost** [ohmcodes/WindowsGSM.Sunkenland#2]
So as the title says, I can not install Sunken Land at all. I have tried removing plugin and reinstalling it. I have re downloaded the plugin and still no success. After reloading the plugin I have restarted WindowsGSM and still wont install. I can literally install EVERY game server, except sunken land. It TRIES to but will only create servers/4/serverfiles/steamapps, servers/4/serverfiles and servers/4/configs, however they are all empty. I tested out installing Ark Ascended installed fine. I tested Rust installed fine, checked space engineers, installed fine. This one with Sunken Land I receive an error in the install progress bar saying "Fail to install [ERROR]" Nothing else no log of errors or anything else. Im not sure what else to do with WindowsGSM, but its been a real pain in my butt.

**Comment by ohmcodes** [comment]
> So as the title says, I can not install Sunken Land at all. I have tried removing plugin and reinstalling it. I have re downloaded the plugin and still no success. After reloading the plugin I have restarted WindowsGSM and still wont install. I can literally install EVERY game server, except sunken land. It TRIES to but will only create servers/4/serverfiles/steamapps, servers/4/serverfiles and servers/4/configs, however they are all empty. I tested out installing Ark Ascended installed fine. I tested Rust installed fine, checked space engineers, installed fine. This one with Sunken Land I receive an error in the install progress bar saying "Fail to install [ERROR]" Nothing else no log of errors or anything else. Im not sure what else to do with WindowsGSM, but its been a real pain in my butt.

have you tried to install sunken land manually? like on steamCMD? if that successfully installed with SteamCMD you can blame my plugin or WGSM itself, this app is just using SteamCMD and run the servers with ease, try to start investigating with server DRM you might need to login your steam with WGSM before downloading this server or try to install steam launcher on your server machine that fix most issues

**Comment by ghost** [comment]
Yes, I can install manually using steamcmd. Its definately with the plugin or windowsgsm. I have been able to install other games that require plugins such as the front just fine. I cant get sunkenland to install using this.

**Comment by ghost** [comment]
So it appears it is 100% plugin, ONLY after putting in my password and username for steam it was able to install. (well it says it is installing, but after looking the files are not being downloaded). However with steamcmd I can do it 100% anonymous.

**Comment by ghost** [comment]
Although, I guess I will still need to install without the plugin. It says installing but no files are even being processed 
![image](https://github.com/ohmcodes/WindowsGSM.Sunkenland/assets/12666699/5a3950fa-dd3e-4539-8030-d5fd938b7a0b)
![image](https://github.com/ohmcodes/WindowsGSM.Sunkenland/assets/12666699/5809c2ef-3698-412b-96ed-30ac49ce1bd8)

**Comment by ohmcodes** [comment]
did you set your account on WGSM? steam account so you can download the dedicated server files also check the notes on login so you can see whats supported or what not, like the steam login with steam guard

**Comment by ghost** [comment]
Yes I did. I gave up on it for a while. Ended up installing without windows GSM. Its weird that this plugin requires a username and password, while ark, rust, and all others dont. That said even when I put in my info it still failed. I have since installed it manually and working fine, and cant even import it in windows gsm. I receive failed to find packageinfo.bin.

![image](https://github.com/ohmcodes/WindowsGSM.Sunkenland/assets/12666699/d6ce4241-5138-4c6d-a1bd-4ee7f945f0bc)
Would have been nice to use WindowsGSM

**Comment by matman82** [comment]
I'm having the same issue! I can install it anonymously with CMD and all works well, but I can't install or import with GSM. Trying to install it just says "Fail to install [ERROR]" and trying to import it says "Invalid path! Fail to find packageinfo.bin". I'm not sure if it's GSM, the plugin, or the janky @$$ game itself! lol I'm kinda leaning towards the later tbh.
